### ISSUE TITLE
Why promise is needed in exercise 6? 

### ISSUE THREAD

**Issue by pom421** [kentcdodds/testing-react-apps#12]
https://github.com/kentcdodds/testing-react-apps/blob/14a317874d2ed320f3396ec4aa2437552678d3e0/src/__tests__/final/06.js#L31

Hi Kent, 

I don't understand why the promise is needed for the 6th exercise. 

Won't this be enough ?

```js
      window.navigator.geolocation.getCurrentPosition = jest.fn().mockImplementation(
              (success, error) => success(fakePosition))

```

Or maybe are you trying to introduce some async work to be closer to reality?

**Comment by kentcdodds** [comment]
Exactly, because the API is async, I want to make sure that any code using it is also async. Additionally, if we just call `success` instantly, then we won't be able to assert the loading state :)

**Comment by pom421** [comment]
That makes sense, thx Kent! 👍 😄

**Comment by sashrika** [comment]
https://github.com/bsonntag/react-use-geolocation/blob/main/src/use-current-position.js

Here that external library calls the getCurrentPosition() method inside an useEffect. In that case, at the time <Location> component is mounted, it should be rendering the Spinner. 
Can't we assume the first `expect` will see this spinner? 
Can't we assume the next 'expect' will see this spinner automatically goes away?

**Comment by kentcdodds** [comment]
@sashrika all `useEffect`s are called synchronously when using React Testing Library because we auto-wrap everything in `act`. This is intentional because that's basically the user's experience anyway (it's extremely rare that a user would ever observe the state of the app between render and useEffect. So if you give it a try you'll notice that no, you can't call the callback synchronously and assert the loading state as well.
