### ISSUE TITLE
Typo in the sidebar on epicreact.dev

### ISSUE THREAD

**Issue by RobbertWolfs** [kentcdodds/testing-react-apps#30]
I think the extra credit of exercise 3 has a typo?

It says `Accertions` instead of `Assertions`?

![image](https://user-images.githubusercontent.com/12511178/95729579-5fa49900-0c7d-11eb-9b42-34e271827aa4.png)

**Comment by kentcdodds** [comment]
Good catch! We'll get that fixed

--- original message ---
On October 12, 2020, 5:25 AM EDT notifications@github.com wrote:



I think the extra credit of exercise 3 has a typo?

It says Accertions instead of Assertions?


—

You are receiving this because you are subscribed to this thread.

Reply to this email directly, view it on GitHub, or unsubscribe.
--- end of original message ---

**Comment by vasilii-kovalev** [comment]
I can see that it is fixed:
![image](https://user-images.githubusercontent.com/10310491/97219072-8c5ac380-17da-11eb-8edf-78cce2a3127c.png)

**Comment by kentcdodds** [comment]
@all-contributors please add @RobbertWolfs for bugs
