### ISSUE TITLE
Mocking HTTP Requests: missing instructions for "Mocked Responses Solution 2" video?

### ISSUE THREAD

**Issue by junagao** [kentcdodds/testing-react-apps#98]
Are the instructions for the "Mocked Responses Solution 2" video missing in the `05.md` file?

I got a bit confused because after doing the "Exercise", which I assume corresponds to the "Mock Service Worker Solution 1" video.. I went directly to do the first extra credit "reuse server request handlers", which corresponds to the third solution video instead.

<img width="1481" alt="Screenshot 2024-01-30 at 16 48 50" src="https://github.com/kentcdodds/testing-react-apps/assets/615616/341bc554-9d15-4902-a519-8fb4ba60b437">

<img width="616" alt="Screenshot 2024-01-30 at 16 47 57" src="https://github.com/kentcdodds/testing-react-apps/assets/615616/671386ce-198a-4da3-8904-cf07213822a3">

**Comment by kentcdodds** [comment]
Hello @junagao,

Sometimes the solutions are so long we split them into two. That's why it's "Solution 1" and "Solution 2" before getting into the "Extra Credit Solution" bits.

I hope that helps! FWIW, in the future, Epic React will be updated to use a much more cohesive workshop environment so the videos are inline with your instructions so you never have to worry about lining up the video with the exercise you're working on. If you're curious what this looks like, check this out: https://www.epicweb.dev/get-started
